[servers]
YOUR_SERVER_IP # IP-адрес целевого VPS

[servers:vars]
ansible_user=debian # Дефолтный пользователь ОС на VPS
ansible_ssh_private_key_file=~/.ssh/id_ed25519_vps # Путь к приватному SSH-ключу