---
- name: Create project directory
  file:
    path: "{{ app_dir }}"
    state: directory

- name: Create Laravel source directory
  file:
    path: "{{ app_dir }}/src"
    state: directory

- name: Install git
  apt:
    name: git
    state: present

- name: Create Laravel project
  command:
    cmd: >
      docker run --rm
      -v {{ app_dir }}/src:/app
      composer:2
      create-project laravel/laravel .
  args:
    creates: "{{ app_dir }}/src/artisan"

# КРИТИЧЕСКИ ВАЖНО: Выставляем права владельца www-data (id 33) на созданные root-ом папки Laravel
- name: Fix storage and cache permissions
  file:
    path: "{{ item }}"
    owner: "33"
    group: "33"
    recurse: yes
  loop:
    - "{{ app_dir }}/src/storage"
    - "{{ app_dir }}/src/bootstrap/cache"

- name: Render docker compose
  template:
    src: docker-compose.yml.j2
    dest: "{{ app_dir }}/docker-compose.yml"
  notify: restart stack

- name: Render nginx config
  template:
    src: default.conf.j2
    dest: "{{ app_dir }}/default.conf"
  notify: restart stack

- name: Render Dockerfile
  template:
    src: Dockerfile.j2
    dest: "{{ app_dir }}/Dockerfile"
  notify: restart stack

- name: Render entrypoint
  template:
    src: entrypoint.sh.j2
    dest: "{{ app_dir }}/entrypoint.sh"
    mode: "0755"
  notify: restart stack

- name: Render env
  template:
    src: .env.j2
    dest: "{{ app_dir }}/src/.env"

- name: Start stack
  community.docker.docker_compose_v2:
    project_src: "{{ app_dir }}"
    state: present
